package buscaminas;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JToggleButton;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Leo
 */
public class Gui extends javax.swing.JFrame implements Jugable,Cronometrable{
    

  


    /**
     * Creates new form Gui
     */
    Game game;
    private int modo = Game.BASICO;
    JToggleButton botones[][] = new JToggleButton['h']['h'];
    private int numClick = 0;
    Cronometro cron = new Cronometro(this);
    int marcados;

    public Gui() {

        initComponents();
        initializeGame(modo);


    }

    public void initializeGame(int modo) {

        game = new Game(modo);
        cron.pararCronometro();
        numClick =0;
        marcados = Game.NUM_BOMBAS;
        jPanel2.removeAll();
        jPanel2.setLayout(new java.awt.GridLayout(Game.NUM_COLUMNAS, Game.NUM_FILAS));
        jLabelBombas.setText("Minas : "+Game.NUM_BOMBAS);
        jLabelTiempo.setText("00:00:00");
        jLabelBombas.setText("Minas : "+Game.NUM_BOMBAS);
        for (int i = 0; i < Game.NUM_FILAS; i++) {
            for (int j = 0; j < Game.NUM_COLUMNAS; j++) {
                JToggleButton b = new JToggleButton("");
                b.setPreferredSize(new Dimension(10, 20));
                b.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background.png")));
                botones[i][j] = b;
                MatrixButtonListener lis = new MatrixButtonListener(i,j,this);
                b.addActionListener(lis);
                b.addMouseListener(new MatrixButtonListener(i,j,this));
                jPanel2.add(b);

            }
        }
                pack();
        jPanel1.revalidate();

        setLocationRelativeTo(null);
    }
    
        public void personalizarJuego(int filas, int columnas,int bombas) {

  
        game = new Game(filas,columnas,bombas);
        cron.pararCronometro();
        numClick =0;
        marcados = Game.NUM_BOMBAS;
        jPanel2.removeAll();
        jPanel2.setLayout(new java.awt.GridLayout(Game.NUM_COLUMNAS, Game.NUM_FILAS));
        jLabelBombas.setText("Minas : "+Game.NUM_BOMBAS);
        jLabelTiempo.setText("00:00:00");
        jLabelBombas.setText("Minas : "+Game.NUM_BOMBAS);
        for (int i = 0; i < Game.NUM_FILAS; i++) {
            for (int j = 0; j < Game.NUM_COLUMNAS; j++) {
                JToggleButton b = new JToggleButton("");
                b.setPreferredSize(new Dimension(10, 20));
                b.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background.png")));
                botones[i][j] = b;
                MatrixButtonListener lis = new MatrixButtonListener(i,j,this);
                b.addActionListener(lis);
                b.addMouseListener(new MatrixButtonListener(i,j,this));
                jPanel2.add(b);

            }
        }
                pack();
        jPanel1.revalidate();

        setLocationRelativeTo(null);

    }


    public void perder() {
        for (int i = 0; i < Game.NUM_FILAS; i++) {
            for (int j = 0; j < Game.NUM_COLUMNAS; j++) {
                if (Game.getCasilla(i, j).getEstaMinado()) {
                    botones[i][j].setText("");
                    botones[i][j].setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_bomb.png")));
                    botones[i][j].setBackground(Color.red);
                }
                botones[i][j].setEnabled(false);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        modosJuegoGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabelBombas = new javax.swing.JLabel();
        jLabelTiempo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();
        jToggleButton4 = new javax.swing.JToggleButton();
        jToggleButton5 = new javax.swing.JToggleButton();
        jToggleButton6 = new javax.swing.JToggleButton();
        jToggleButton7 = new javax.swing.JToggleButton();
        jToggleButton8 = new javax.swing.JToggleButton();
        jToggleButton9 = new javax.swing.JToggleButton();
        jToggleButton10 = new javax.swing.JToggleButton();
        jToggleButton11 = new javax.swing.JToggleButton();
        jToggleButton12 = new javax.swing.JToggleButton();
        jToggleButton13 = new javax.swing.JToggleButton();
        jToggleButton14 = new javax.swing.JToggleButton();
        jToggleButton15 = new javax.swing.JToggleButton();
        jToggleButton16 = new javax.swing.JToggleButton();
        jToggleButton17 = new javax.swing.JToggleButton();
        jToggleButton18 = new javax.swing.JToggleButton();
        jToggleButton19 = new javax.swing.JToggleButton();
        jToggleButton20 = new javax.swing.JToggleButton();
        jToggleButton21 = new javax.swing.JToggleButton();
        jToggleButton22 = new javax.swing.JToggleButton();
        jToggleButton23 = new javax.swing.JToggleButton();
        jToggleButton24 = new javax.swing.JToggleButton();
        jToggleButton25 = new javax.swing.JToggleButton();
        jToggleButton26 = new javax.swing.JToggleButton();
        jToggleButton27 = new javax.swing.JToggleButton();
        jToggleButton28 = new javax.swing.JToggleButton();
        jToggleButton29 = new javax.swing.JToggleButton();
        jToggleButton30 = new javax.swing.JToggleButton();
        jToggleButton31 = new javax.swing.JToggleButton();
        jToggleButton32 = new javax.swing.JToggleButton();
        jToggleButton33 = new javax.swing.JToggleButton();
        jToggleButton34 = new javax.swing.JToggleButton();
        jToggleButton35 = new javax.swing.JToggleButton();
        jToggleButton36 = new javax.swing.JToggleButton();
        jToggleButton37 = new javax.swing.JToggleButton();
        jToggleButton38 = new javax.swing.JToggleButton();
        jToggleButton39 = new javax.swing.JToggleButton();
        jToggleButton40 = new javax.swing.JToggleButton();
        jToggleButton41 = new javax.swing.JToggleButton();
        jToggleButton42 = new javax.swing.JToggleButton();
        jToggleButton43 = new javax.swing.JToggleButton();
        jToggleButton44 = new javax.swing.JToggleButton();
        jToggleButton45 = new javax.swing.JToggleButton();
        jToggleButton46 = new javax.swing.JToggleButton();
        jToggleButton47 = new javax.swing.JToggleButton();
        jToggleButton48 = new javax.swing.JToggleButton();
        jToggleButton49 = new javax.swing.JToggleButton();
        jToggleButton50 = new javax.swing.JToggleButton();
        jToggleButton51 = new javax.swing.JToggleButton();
        jToggleButton52 = new javax.swing.JToggleButton();
        jToggleButton53 = new javax.swing.JToggleButton();
        jToggleButton54 = new javax.swing.JToggleButton();
        jToggleButton55 = new javax.swing.JToggleButton();
        jToggleButton56 = new javax.swing.JToggleButton();
        jToggleButton57 = new javax.swing.JToggleButton();
        jToggleButton58 = new javax.swing.JToggleButton();
        jToggleButton59 = new javax.swing.JToggleButton();
        jToggleButton60 = new javax.swing.JToggleButton();
        jToggleButton61 = new javax.swing.JToggleButton();
        jToggleButton62 = new javax.swing.JToggleButton();
        jToggleButton63 = new javax.swing.JToggleButton();
        jToggleButton64 = new javax.swing.JToggleButton();
        jToggleButton65 = new javax.swing.JToggleButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jRadioButtonMenuItem2 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem3 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem4 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem5 = new javax.swing.JRadioButtonMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Buscaminas");
        setIconImage(Toolkit.getDefaultToolkit().getImage(Gui.class.getResource("/images/icono.png")));

        jPanel1.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                jPanel1ComponentAdded(evt);
            }
        });

        jLabelBombas.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jLabelBombas.setText("10");

        jLabelTiempo.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jLabelTiempo.setText("00:00");
        jLabelTiempo.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jLabelTiempo.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                jLabelTiempoVetoableChange(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelBombas, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelBombas)
                    .addComponent(jLabelTiempo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setLayout(new java.awt.GridLayout(8, 8));

        jToggleButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pin.png"))); // NOI18N
        jPanel2.add(jToggleButton2);

        jToggleButton3.setText("0");
        jPanel2.add(jToggleButton3);

        jToggleButton4.setText("0");
        jPanel2.add(jToggleButton4);

        jToggleButton5.setText("0");
        jPanel2.add(jToggleButton5);

        jToggleButton6.setText("0");
        jPanel2.add(jToggleButton6);

        jToggleButton7.setText("0");
        jPanel2.add(jToggleButton7);

        jToggleButton8.setText("0");
        jPanel2.add(jToggleButton8);

        jToggleButton9.setText("0");
        jPanel2.add(jToggleButton9);

        jToggleButton10.setText("0");
        jPanel2.add(jToggleButton10);

        jToggleButton11.setText("0");
        jPanel2.add(jToggleButton11);

        jToggleButton12.setText("0");
        jPanel2.add(jToggleButton12);

        jToggleButton13.setText("0");
        jPanel2.add(jToggleButton13);

        jToggleButton14.setText("0");
        jPanel2.add(jToggleButton14);

        jToggleButton15.setText("0");
        jPanel2.add(jToggleButton15);

        jToggleButton16.setText("0");
        jPanel2.add(jToggleButton16);

        jToggleButton17.setText("0");
        jPanel2.add(jToggleButton17);

        jToggleButton18.setText("0");
        jPanel2.add(jToggleButton18);

        jToggleButton19.setText("0");
        jPanel2.add(jToggleButton19);

        jToggleButton20.setText("0");
        jPanel2.add(jToggleButton20);

        jToggleButton21.setText("0");
        jPanel2.add(jToggleButton21);

        jToggleButton22.setText("0");
        jPanel2.add(jToggleButton22);

        jToggleButton23.setText("0");
        jToggleButton23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jToggleButton23MouseReleased(evt);
            }
        });
        jPanel2.add(jToggleButton23);

        jToggleButton24.setText("0");
        jPanel2.add(jToggleButton24);

        jToggleButton25.setText("0");
        jPanel2.add(jToggleButton25);

        jToggleButton26.setText("0");
        jPanel2.add(jToggleButton26);

        jToggleButton27.setText("0");
        jPanel2.add(jToggleButton27);

        jToggleButton28.setText("0");
        jPanel2.add(jToggleButton28);

        jToggleButton29.setText("0");
        jPanel2.add(jToggleButton29);

        jToggleButton30.setText("0");
        jPanel2.add(jToggleButton30);

        jToggleButton31.setText("0");
        jPanel2.add(jToggleButton31);

        jToggleButton32.setText("0");
        jPanel2.add(jToggleButton32);

        jToggleButton33.setText("0");
        jPanel2.add(jToggleButton33);

        jToggleButton34.setText("0");
        jPanel2.add(jToggleButton34);

        jToggleButton35.setText("0");
        jPanel2.add(jToggleButton35);

        jToggleButton36.setText("0");
        jPanel2.add(jToggleButton36);

        jToggleButton37.setText("0");
        jPanel2.add(jToggleButton37);

        jToggleButton38.setText("0");
        jPanel2.add(jToggleButton38);

        jToggleButton39.setText("0");
        jPanel2.add(jToggleButton39);

        jToggleButton40.setText("0");
        jPanel2.add(jToggleButton40);

        jToggleButton41.setText("0");
        jPanel2.add(jToggleButton41);

        jToggleButton42.setText("0");
        jPanel2.add(jToggleButton42);

        jToggleButton43.setText("0");
        jPanel2.add(jToggleButton43);

        jToggleButton44.setText("0");
        jPanel2.add(jToggleButton44);

        jToggleButton45.setText("0");
        jPanel2.add(jToggleButton45);

        jToggleButton46.setText("0");
        jPanel2.add(jToggleButton46);

        jToggleButton47.setText("0");
        jPanel2.add(jToggleButton47);

        jToggleButton48.setText("0");
        jPanel2.add(jToggleButton48);

        jToggleButton49.setText("0");
        jPanel2.add(jToggleButton49);

        jToggleButton50.setText("0");
        jPanel2.add(jToggleButton50);

        jToggleButton51.setText("0");
        jPanel2.add(jToggleButton51);

        jToggleButton52.setText("0");
        jPanel2.add(jToggleButton52);

        jToggleButton53.setText("0");
        jPanel2.add(jToggleButton53);

        jToggleButton54.setText("0");
        jPanel2.add(jToggleButton54);

        jToggleButton55.setText("0");
        jPanel2.add(jToggleButton55);

        jToggleButton56.setText("0");
        jPanel2.add(jToggleButton56);

        jToggleButton57.setText("0");
        jPanel2.add(jToggleButton57);

        jToggleButton58.setText("0");
        jPanel2.add(jToggleButton58);

        jToggleButton59.setText("0");
        jPanel2.add(jToggleButton59);

        jToggleButton60.setText("0");
        jPanel2.add(jToggleButton60);

        jToggleButton61.setText("0");
        jPanel2.add(jToggleButton61);

        jToggleButton62.setText("0");
        jPanel2.add(jToggleButton62);

        jToggleButton63.setText("0");
        jPanel2.add(jToggleButton63);

        jToggleButton64.setText("0");
        jPanel2.add(jToggleButton64);

        jToggleButton65.setText("0");
        jPanel2.add(jToggleButton65);

        jMenu1.setText("Juego");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Juego nuevo");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        modosJuegoGroup.add(jRadioButtonMenuItem2);
        jRadioButtonMenuItem2.setSelected(true);
        jRadioButtonMenuItem2.setText("Basico");
        jRadioButtonMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jRadioButtonMenuItem2);

        modosJuegoGroup.add(jRadioButtonMenuItem3);
        jRadioButtonMenuItem3.setText("Normal");
        jRadioButtonMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jRadioButtonMenuItem3);

        modosJuegoGroup.add(jRadioButtonMenuItem4);
        jRadioButtonMenuItem4.setText("Experto");
        jRadioButtonMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jRadioButtonMenuItem4);

        modosJuegoGroup.add(jRadioButtonMenuItem5);
        jRadioButtonMenuItem5.setText("Personalizar");
        jRadioButtonMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jRadioButtonMenuItem5);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ayuda");

        jMenuItem2.setText("Instrucciones");
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem5ActionPerformed
        // TODO add your handling code here:
        NewDialog dialog = new NewDialog(this,true);
        Values values = dialog.showDialog();
        if(values != null){
            personalizarJuego(values.getRows(),values.getColumns(),values.getBombs());
        }else{
           // System.out.println("Cancelado por usuario");
        }
    }//GEN-LAST:event_jRadioButtonMenuItem5ActionPerformed

    private void jRadioButtonMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem2ActionPerformed
        // TODO add your handling code here:
        modo = Game.BASICO;
        initializeGame(modo);
    }//GEN-LAST:event_jRadioButtonMenuItem2ActionPerformed

    private void jRadioButtonMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem3ActionPerformed
        // TODO add your handling code here:
        modo = Game.NORMAL;
        initializeGame(modo);
    }//GEN-LAST:event_jRadioButtonMenuItem3ActionPerformed

    private void jRadioButtonMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem4ActionPerformed
        // TODO add your handling code here:
        modo = Game.AVANZADO;
        initializeGame(modo);
    }//GEN-LAST:event_jRadioButtonMenuItem4ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        initializeGame(modo);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jToggleButton23MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton23MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton23MouseReleased

    private void jLabelTiempoVetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_jLabelTiempoVetoableChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelTiempoVetoableChange

    private void jPanel1ComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jPanel1ComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1ComponentAdded

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Gui.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(Gui.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(Gui.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(Gui.class.getName()).log(Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelBombas;
    private javax.swing.JLabel jLabelTiempo;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem2;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem3;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem4;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem5;
    private javax.swing.JToggleButton jToggleButton10;
    private javax.swing.JToggleButton jToggleButton11;
    private javax.swing.JToggleButton jToggleButton12;
    private javax.swing.JToggleButton jToggleButton13;
    private javax.swing.JToggleButton jToggleButton14;
    private javax.swing.JToggleButton jToggleButton15;
    private javax.swing.JToggleButton jToggleButton16;
    private javax.swing.JToggleButton jToggleButton17;
    private javax.swing.JToggleButton jToggleButton18;
    private javax.swing.JToggleButton jToggleButton19;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton20;
    private javax.swing.JToggleButton jToggleButton21;
    private javax.swing.JToggleButton jToggleButton22;
    private javax.swing.JToggleButton jToggleButton23;
    private javax.swing.JToggleButton jToggleButton24;
    private javax.swing.JToggleButton jToggleButton25;
    private javax.swing.JToggleButton jToggleButton26;
    private javax.swing.JToggleButton jToggleButton27;
    private javax.swing.JToggleButton jToggleButton28;
    private javax.swing.JToggleButton jToggleButton29;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToggleButton jToggleButton30;
    private javax.swing.JToggleButton jToggleButton31;
    private javax.swing.JToggleButton jToggleButton32;
    private javax.swing.JToggleButton jToggleButton33;
    private javax.swing.JToggleButton jToggleButton34;
    private javax.swing.JToggleButton jToggleButton35;
    private javax.swing.JToggleButton jToggleButton36;
    private javax.swing.JToggleButton jToggleButton37;
    private javax.swing.JToggleButton jToggleButton38;
    private javax.swing.JToggleButton jToggleButton39;
    private javax.swing.JToggleButton jToggleButton4;
    private javax.swing.JToggleButton jToggleButton40;
    private javax.swing.JToggleButton jToggleButton41;
    private javax.swing.JToggleButton jToggleButton42;
    private javax.swing.JToggleButton jToggleButton43;
    private javax.swing.JToggleButton jToggleButton44;
    private javax.swing.JToggleButton jToggleButton45;
    private javax.swing.JToggleButton jToggleButton46;
    private javax.swing.JToggleButton jToggleButton47;
    private javax.swing.JToggleButton jToggleButton48;
    private javax.swing.JToggleButton jToggleButton49;
    private javax.swing.JToggleButton jToggleButton5;
    private javax.swing.JToggleButton jToggleButton50;
    private javax.swing.JToggleButton jToggleButton51;
    private javax.swing.JToggleButton jToggleButton52;
    private javax.swing.JToggleButton jToggleButton53;
    private javax.swing.JToggleButton jToggleButton54;
    private javax.swing.JToggleButton jToggleButton55;
    private javax.swing.JToggleButton jToggleButton56;
    private javax.swing.JToggleButton jToggleButton57;
    private javax.swing.JToggleButton jToggleButton58;
    private javax.swing.JToggleButton jToggleButton59;
    private javax.swing.JToggleButton jToggleButton6;
    private javax.swing.JToggleButton jToggleButton60;
    private javax.swing.JToggleButton jToggleButton61;
    private javax.swing.JToggleButton jToggleButton62;
    private javax.swing.JToggleButton jToggleButton63;
    private javax.swing.JToggleButton jToggleButton64;
    private javax.swing.JToggleButton jToggleButton65;
    private javax.swing.JToggleButton jToggleButton7;
    private javax.swing.JToggleButton jToggleButton8;
    private javax.swing.JToggleButton jToggleButton9;
    private javax.swing.ButtonGroup modosJuegoGroup;
    // End of variables declaration//GEN-END:variables

    @Override
    public void onPerder() {
       cron.pararCronometro();
       perder();
    }

    @Override
    public void onAcertarMina() {
      }

    @Override
    public void onMinaVacia() {
     }

    @Override
    public void updateGui(String text) {
        jLabelTiempo.setText(text);

      }
    
    @Override
    public void onClick(){
        if (numClick == 0) {
            cron.iniciarCronometro();
        }
        numClick++;
    }
    
    @Override
    public void onMarcarMina(){
    marcados--;
    jLabelBombas.setText("Minas : " + marcados);
    }

    @Override
    public void onDesmarcarMina() {
    marcados++; 
    jLabelBombas.setText("Minas : "+marcados);
    }
}
